import fs from 'fs'

import { ES2022, semanticsES2022 } from "./grammars/ES2022.js"

function main() {
  let output = "// This file has been automatically generated by jsdoc-to-d-ts\n"

  const content = fs.readFileSync('test.ignore.js', 'utf-8')

  const match = ES2022.match(content, 'File')

  const file = semanticsES2022(match)

  for (const _class of file.eval()) {
    console.log(JSON.stringify(_class.methods[1].doc, null, 4))
  }
}

main()
